# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16028064e46e73a6b827f1e67a1a185bd129fed17c471788558b0084a968efae90ecf4433b03d1de561490fa9588310b5c644cf060e9b211f7a693710b2237c5

test:
  secret_key_base: 7a0520ab90e0f9eaacf76de6ec6cacd84a12e10e252fda3686761ee0fa412f9dbcd113343e868dfffac050f031e8f11376ed021fb8bbbac8ecf563a4d064597c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
